/*
 * sig.h
 *
 *  Created on: 2017Äê12ÔÂ14ÈÕ
 *      Author: zjm09
 */

#ifndef FRAMEWORK_SIG_H_
#define FRAMEWORK_SIG_H_

enum{
	MSG_TIME_MIN_1 = 10,
	MSG_TIME_MIN_5,		// 11
	MSG_TIME_HOUR,		// 12
	MSG_TIME_DAY,		// 13
	MSG_TIME_MONTH,		// 14
	MSG_DATA_GET,		// 15
	MSG_DATA_SET,		// 16
	MSG_CONF_GET,		// 17
	MSG_CONF_SET,		// 18
	MSG_NET_CONNECT,	// 19
	MSG_NET_CONNECTED,	// 20
	MSG_NET_RECONNECT,	// 21
	MSG_NET_CLOSE,		// 22
	MSG_NET_CLOSED,		// 23
	MSG_NET_INIT,		// 24
	MSG_NET_RADEY,		// 25
	MSG_NET_SMS_SEND,	// 26
	MSG_NET_GPRS_SEND,	// 27
	MSG_NET_RECV,		// 28
	MSG_NET_HEARTBEAT,	// 29
	MSG_SERIAL_RECV,	// 30
	MSG_SERIAL_RECONFIG,// 31
	MSG_SEND_VOLTAGE,	// 32
	MSG_SEND_DAY,		// 33
	MSG_SEND_MONTH,		// 34
	MSG_LOST_POWER,		// 35
	MSG_POWER_ON,		// 36
	MSG_WAKEUP,			// 37
	MSG_KEY,			// 38
	MSG_TIMER,			// 39
	MSG_INIT,			// 30
	MSG_DATACLEAR,		// 40
	MSG_EVENT,			// 41
	MSG_SEND_AGAIN,		// 42
	MSG_KEY_DOWN,		// 43
	MSG_SAVE_COFF,		// 44
	MSG_SEND_SMS,		// 45
	MSG_SEND_EVENT,		// 46
	MSG_SEND_FLOW,		// 47
	MSG_GPRS_CSQ,		// 48
	MSG_prepare_sleep,	// 49
	MSG_SEND_REAL_VAL,	// 50
	MSG_RESTORE,		// 51
	MSG_NET_LINKED,     // 52
	MSG_POWER_SMS,      // 53
	MSG_DATA_GET_MON,   // 54
	MSG_DATA_GET_DAY,   // 55
	MSG_DATA_GET_MIN,   // 56
	MSG_GET_EVENT,      // 57
	MSG_GET_EVENT_MAXID,// 58
	MSG_RESET,          // 59
	MSG_UPDATE,         // 60
	MSG_DO_UPDATE,      // 61
	MSG_SET_DAY_DATA,   // 62
	MSG_SET_MON_DATA,   // 63
	MSG_FORWARD,        // 64
	MSG_NET_LOGIN,      // 65
	EVENT_IN_TESTING,   // 66
	EVENT_OUT_TESTING,  // 67
	MSG_NET_RECONFIG,   // 68
	MSG_DESTROY,        // 69
	MSG_DO_SQL,			// 70
};

#endif /* FRAMEWORK_SIG_H_ */
